name: Build And Deploy With Docker

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  RELEASE_LABEL: ${{ github.sha }}
  APP_NAME: ${{ github.event.repository.name }}

  
jobs:
  build:
    name: Build image and push to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Build Docker Image
        run: |
            echo ${{secrets.DOCKERREGISTRYPASS}} | docker login -u rodolfofadino --password-stdin
            docker build . -t fiap
            docker push rodolfofadino/fiap:latest

    
    
  
